#! /bin/bash

zenity --file-selection

lenfile=$(cat autopatcher/unl/file.out | sed 's/|//')

python "$(dirname "$(realpath $0)")/autopatcher/patch/autopatch.py" "$lenfile" > autopatcher/unl/patch.out | zenity --progress --title="Unlocking bin File..." --text="Patching Bin..." --width=300 --auto-close --auto-kill --pulsate --time-remaining --percentage=100

if grep -q error "autopatcher/unl/patch.out"; then
  zenity --height=100 --width=300 --info --text="<big>Bin Patching Failed</big>" --no-wrap
else
  zenity --height=100 --width=300 --info --text="<big>Bin Patching is Complete!</big>" --no-wrap
fi



